# Visit https://github.com/lowlighter/metrics#-documentation for full reference
- name: Metrics embed
  uses: lowlighter/metrics@v3.34
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_lines: yes
          template: markdown
          plugin_activity: yes
